backend:
  name: git-gateway
  repo: aliasttt/hedefsurucukursu
  branch: main
  base_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "assets/img"
public_folder: "/assets/img"

site_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
display_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
logo_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr/assets/img/logo.png
site_name: "Hedef Sürücü Kursu"
site_description: "Hedef Sürücü Kursu, profesyonel sürücü eğitimi ve danışmanlık hizmetleri sunar. Amacımız, güvenli ve bilinçli sürücüler yetiştirmektir."

# اضافه کردن تنظیمات جدید برای رفع مشکل ریدایرکت
local_backend: true
load_config_file: true

collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - { label: "Ana Görsel", name: "hero", widget: "image" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      - label: "Hakkımızda"
        name: "about"
        file: "hakkimizda.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - { label: "Görsel", name: "image", widget: "image" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      - label: "Kurs Fiyatları"
        name: "prices"
        file: "kurs-fiyatlarimiz.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - label: "Fiyat Kartları"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Kart Başlık", name: "card_title", widget: "string" }
              - { label: "Kart Açıklama", name: "card_desc", widget: "text" }
              - { label: "Kart Fiyatı", name: "card_price", widget: "string" }
              - { label: "Kart Görseli", name: "card_image", widget: "image" }
      - label: "İletişim"
        name: "contact"
        file: "contact.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Adres", name: "address", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "E-posta", name: "email", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
      - label: "Sıkça Sorulan Sorular"
        name: "faq"
        file: "sikca-sorulan-sorular.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      - label: "Duyurular"
        name: "announcements"
        file: "duyurular.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - { label: "Görsel", name: "image", widget: "image" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      - label: "Ekibimiz"
        name: "team"
        file: "ekibimiz.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - label: "Ekip Üyeleri"
            name: "members"
            widget: "list"
            fields:
              - { label: "İsim", name: "name", widget: "string" }
              - { label: "Pozisyon", name: "position", widget: "string" }
              - { label: "Fotoğraf", name: "photo", widget: "image" }
              - { label: "Açıklama", name: "description", widget: "text" }
      - label: "Kursumuz"
        name: "courses"
        file: "kursumuz.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "desc", widget: "text" }
          - label: "Dersler"
            name: "lessons"
            widget: "list"
            fields:
              - { label: "Ders Başlık", name: "lesson_title", widget: "string" }
              - { label: "Ders Açıklama", name: "lesson_desc", widget: "text" }
              - { label: "Ders Görseli", name: "lesson_image", widget: "image" }
      - label: "Yorumlar"
        name: "comments"
        file: "yorumlar.html"
        fields:
          - label: "Yorumlar Listesi"
            name: "comments_list"
            widget: "list"
            fields:
              - { label: "İsim", name: "name", widget: "string" }
              - { label: "Yorum", name: "comment", widget: "text" }
              - { label: "Avatar", name: "avatar", widget: "image" }

  - name: "images"
    label: "Görseller"
    files:
      - label: "Görsel Yönetimi"
        name: "images"
        file: "assets/img/images.yml"
        fields:
          - { label: "Görsel", name: "image", widget: "image" }
          - { label: "Açıklama", name: "caption", widget: "string" }
          - { label: "Kategori", name: "category", widget: "select", options: ["hero", "team", "news", "other"] }