backend:
  name: git-gateway
  repo: aliasttt/hedefsurucukursu
  branch: main
  base_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "assets/img"
public_folder: "/assets/img"

site_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
display_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
logo_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr/assets/img/logo.png
site_name: "Hedef Sürücü Kursu"
site_description: "Hedef Sürücü Kursu, profesyonel sürücü eğitimi ve danışmanlık hizmetleri sunar. Amacımız, güvenli ve bilinçli sürücüler yetiştirmektir."

# اضافه کردن تنظیمات جدید برای رفع مشکل ریدایرکت
local_backend: true
load_config_file: true

collections:
  - name: "site_settings"
    label: "Site Ayarları"
    files:
      - label: "Genel Ayarlar"
        name: "general"
        file: "data/settings.json"
        fields:
          - { label: "Site Başlığı", name: "site_title", widget: "string" }
          - { label: "Site Açıklaması", name: "site_description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Favicon", name: "favicon", widget: "image" }
          - { label: "Meta Keywords", name: "meta_keywords", widget: "string" }
          - { label: "Meta Description", name: "meta_description", widget: "text" }

      - label: "İletişim Bilgileri"
        name: "contact"
        file: "data/contact.json"
        fields:
          - { label: "Adres", name: "address", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "E-posta", name: "email", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Facebook", name: "facebook", widget: "string" }
          - { label: "Çalışma Saatleri", name: "working_hours", widget: "text" }
          - { label: "Google Maps Embed URL", name: "maps_url", widget: "string" }

      - label: "Sosyal Medya"
        name: "social"
        file: "data/social.json"
        fields:
          - { label: "Instagram URL", name: "instagram", widget: "string" }
          - { label: "Facebook URL", name: "facebook", widget: "string" }
          - { label: "WhatsApp URL", name: "whatsapp", widget: "string" }
          - { label: "YouTube URL", name: "youtube", widget: "string" }

  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "data/home.json"
        fields:
          - { label: "Hero Başlık", name: "hero_title", widget: "string" }
          - { label: "Hero Alt Başlık", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Görsel", name: "hero_image", widget: "image" }
          - { label: "Hakkımızda Özet", name: "about_summary", widget: "text" }
          - label: "Öne Çıkan Kurslar"
            name: "featured_courses"
            widget: "list"
            fields:
              - { label: "Kurs Adı", name: "title", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "Görsel", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }

      - label: "Hakkımızda"
        name: "about"
        file: "data/about.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Alt Başlık", name: "subtitle", widget: "string" }
          - { label: "Ana Görsel", name: "main_image", widget: "image" }
          - { label: "İçerik", name: "content", widget: "markdown" }
          - label: "Özellikler"
            name: "features"
            widget: "list"
            fields:
              - { label: "Başlık", name: "title", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "İkon", name: "icon", widget: "string" }

      - label: "Kurslar"
        name: "courses"
        file: "data/courses.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "description", widget: "text" }
          - label: "Kurs Listesi"
            name: "course_list"
            widget: "list"
            fields:
              - { label: "Kurs Adı", name: "title", widget: "string" }
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "Fiyat", name: "price", widget: "string" }
              - { label: "Süre", name: "duration", widget: "string" }
              - { label: "Görsel", name: "image", widget: "image" }
              - { label: "İçerik", name: "content", widget: "markdown" }
              - label: "Özellikler"
                name: "features"
                widget: "list"
                fields:
                  - { label: "Özellik", name: "feature", widget: "string" }

      - label: "Duyurular"
        name: "announcements"
        file: "data/announcements.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - label: "Duyuru Listesi"
            name: "announcement_list"
            widget: "list"
            fields:
              - { label: "Başlık", name: "title", widget: "string" }
              - { label: "Tarih", name: "date", widget: "datetime" }
              - { label: "Görsel", name: "image", widget: "image" }
              - { label: "İçerik", name: "content", widget: "markdown" }

      - label: "S.S.S"
        name: "faq"
        file: "data/faq.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - label: "Soru Listesi"
            name: "faq_list"
            widget: "list"
            fields:
              - { label: "Soru", name: "question", widget: "string" }
              - { label: "Cevap", name: "answer", widget: "markdown" }

      - label: "Ekibimiz"
        name: "team"
        file: "data/team.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Açıklama", name: "description", widget: "text" }
          - label: "Ekip Üyeleri"
            name: "team_members"
            widget: "list"
            fields:
              - { label: "İsim", name: "name", widget: "string" }
              - { label: "Pozisyon", name: "position", widget: "string" }
              - { label: "Fotoğraf", name: "photo", widget: "image" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "Sosyal Medya", name: "social_media", widget: "object", fields: [
                  { label: "Instagram", name: "instagram", widget: "string", required: false },
                  { label: "Facebook", name: "facebook", widget: "string", required: false },
                  { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
                ]}

  - name: "images"
    label: "Görseller"
    files:
      - label: "Görsel Yönetimi"
        name: "images"
        file: "data/images.json"
        fields:
          - label: "Görsel Listesi"
            name: "image_list"
            widget: "list"
            fields:
              - { label: "Görsel", name: "image", widget: "image" }
              - { label: "Açıklama", name: "caption", widget: "string" }
              - { label: "Kategori", name: "category", widget: "select", options: ["hero", "team", "news", "other"] }
              - { label: "Alt Text", name: "alt", widget: "string" }