backend:
  name: git-gateway
  repo: aliasttt/hedefsurucukursu
  branch: main
  base_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "assets/img"
public_folder: "/assets/img"

site_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
display_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
logo_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr/assets/img/logo.png
site_name: "Hedef Sürücü Kursu"
site_description: "Hedef Sürücü Kursu, profesyonel sürücü eğitimi ve danışmanlık hizmetleri sunar. Amacımız, güvenli ve bilinçli sürücüler yetiştirmektir."

# اضافه کردن تنظیمات جدید برای رفع مشکل ریدایرکت
local_backend: true
load_config_file: true

collections:
  - name: "home"
    label: "Ana Sayfa"
    files:
      - label: "Ana Sayfa İçeriği"
        name: "home"
        file: "data/home.json"
        fields:
          - { label: "Hero Başlık", name: "hero_title", widget: "string", required: false }
          - { label: "Hero Alt Başlık", name: "hero_subtitle", widget: "string", required: false }
          - { label: "Hero Görsel", name: "hero_image", widget: "image", required: false }
          - { label: "Hero Video", name: "hero_video", widget: "string", required: false }
          - { label: "Hakkımızda Özet", name: "about_summary", widget: "text", required: false }
          - label: "Öne Çıkan Kurslar"
            name: "featured_courses"
            widget: "list"
            fields:
              - { label: "Kurs Adı", name: "title", widget: "string", required: false }
              - { label: "Açıklama", name: "description", widget: "text", required: false }
              - { label: "Görsel", name: "image", widget: "image", required: false }
              - { label: "Video", name: "video", widget: "string", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }

  - name: "about"
    label: "Hakkımızda"
    files:
      - label: "Hakkımızda İçeriği"
        name: "about"
        file: "data/about.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string", required: false }
          - { label: "Alt Başlık", name: "subtitle", widget: "string", required: false }
          - { label: "Ana Görsel", name: "main_image", widget: "image", required: false }
          - { label: "Video", name: "main_video", widget: "string", required: false }
          - { label: "İçerik", name: "content", widget: "markdown", required: false }
          - label: "Özellikler"
            name: "features"
            widget: "list"
            fields:
              - { label: "Başlık", name: "title", widget: "string", required: false }
              - { label: "Açıklama", name: "description", widget: "text", required: false }
              - { label: "İkon", name: "icon", widget: "string", required: false }

  - name: "courses"
    label: "Kurslar"
    files:
      - label: "Kurslar İçeriği"
        name: "courses"
        file: "data/courses.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string", required: false }
          - { label: "Açıklama", name: "description", widget: "text", required: false }
          - label: "Kurs Listesi"
            name: "course_list"
            widget: "list"
            fields:
              - { label: "Kurs Adı", name: "title", widget: "string", required: false }
              - { label: "Slug", name: "slug", widget: "string", required: false }
              - { label: "Açıklama", name: "description", widget: "text", required: false }
              - { label: "Fiyat", name: "price", widget: "string", required: false }
              - { label: "Süre", name: "duration", widget: "string", required: false }
              - { label: "Görsel", name: "image", widget: "image", required: false }
              - { label: "Video", name: "video", widget: "string", required: false }
              - { label: "İçerik", name: "content", widget: "markdown", required: false }
              - label: "Özellikler"
                name: "features"
                widget: "list"
                fields:
                  - { label: "Özellik", name: "feature", widget: "string", required: false }

  - name: "announcements"
    label: "Duyurular"
    files:
      - label: "Duyurular İçeriği"
        name: "announcements"
        file: "data/announcements.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string", required: false }
          - label: "Duyuru Listesi"
            name: "announcement_list"
            widget: "list"
            fields:
              - { label: "Başlık", name: "title", widget: "string", required: false }
              - { label: "Tarih", name: "date", widget: "datetime", required: false }
              - { label: "Görsel", name: "image", widget: "image", required: false }
              - { label: "Video", name: "video", widget: "string", required: false }
              - { label: "İçerik", name: "content", widget: "markdown", required: false }

  - name: "faq"
    label: "Sıkça Sorulan Sorular"
    files:
      - label: "S.S.S İçeriği"
        name: "faq"
        file: "data/faq.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string", required: false }
          - label: "Soru Listesi"
            name: "faq_list"
            widget: "list"
            fields:
              - { label: "Soru", name: "question", widget: "string", required: false }
              - { label: "Cevap", name: "answer", widget: "markdown", required: false }

  - name: "team"
    label: "Ekibimiz"
    files:
      - label: "Ekibimiz İçeriği"
        name: "team"
        file: "data/team.json"
        fields:
          - { label: "Başlık", name: "title", widget: "string", required: false }
          - { label: "Açıklama", name: "description", widget: "text", required: false }
          - label: "Ekip Üyeleri"
            name: "team_members"
            widget: "list"
            fields:
              - { label: "İsim", name: "name", widget: "string", required: false }
              - { label: "Pozisyon", name: "position", widget: "string", required: false }
              - { label: "Fotoğraf", name: "photo", widget: "image", required: false }
              - { label: "Açıklama", name: "description", widget: "text", required: false }
              - label: "Sosyal Medya"
                name: "social_media"
                widget: "object"
                fields:
                  - { label: "Instagram", name: "instagram", widget: "string", required: false }
                  - { label: "Facebook", name: "facebook", widget: "string", required: false }
                  - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

  - name: "contact"
    label: "İletişim"
    files:
      - label: "İletişim Bilgileri"
        name: "contact"
        file: "data/contact.json"
        fields:
          - { label: "Adres", name: "address", widget: "string", required: false }
          - { label: "Telefon", name: "phone", widget: "string", required: false }
          - { label: "E-posta", name: "email", widget: "string", required: false }
          - { label: "WhatsApp", name: "whatsapp", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - label: "Çalışma Saatleri"
            name: "working_hours"
            widget: "list"
            fields:
              - { label: "Gün", name: "day", widget: "string", required: false }
              - { label: "Saat", name: "hours", widget: "string", required: false }
          - { label: "Google Maps Embed URL", name: "maps_url", widget: "string", required: false }

  - name: "images"
    label: "Görseller"
    files:
      - label: "Görsel Yönetimi"
        name: "images"
        file: "data/images.json"
        fields:
          - label: "Görsel Listesi"
            name: "image_list"
            widget: "list"
            fields:
              - { label: "Görsel", name: "image", widget: "image", required: false }
              - { label: "Açıklama", name: "caption", widget: "string", required: false }
              - { label: "Kategori", name: "category", widget: "select", options: ["hero", "team", "news", "other"], required: false }
              - { label: "Alt Text", name: "alt", widget: "string", required: false }