backend:
  name: git-gateway
  repo: aliasttt/hedefsurucukursu
  branch: main
  base_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "assets/img"
public_folder: "/assets/img"

site_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr
logo_url: https://xn--hedefsrckurslar-4vbbb82h.com.tr/assets/img/logo.png
site_name: "Hedef Sürücü Kursu"
site_description: "Hedef Sürücü Kursu, profesyonel sürücü eğitimi ve danışmanlık hizmetleri sunar. Amacımız, güvenli ve bilinçli sürücüler yetiştirmektir."
collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - { label: "Hero Görsel 1", name: "hero1", widget: "image" }
          - { label: "Hero Başlık 1", name: "hero1_title", widget: "string" }
          - { label: "Hero Açıklama 1", name: "hero1_desc", widget: "string" }
          - { label: "Hero Görsel 2", name: "hero2", widget: "image" }
          - { label: "Hero Başlık 2", name: "hero2_title", widget: "string" }
          - { label: "Hero Açıklama 2", name: "hero2_desc", widget: "string" }
          - { label: "Hero Görsel 3", name: "hero3", widget: "image" }
          - { label: "Hero Başlık 3", name: "hero3_title", widget: "string" }
          - { label: "Hero Açıklama 3", name: "hero3_desc", widget: "string" }
      
      - label: "Hakkımızda"
        name: "about"
        file: "hakkimizda.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - { label: "Görsel", name: "image", widget: "image" }
      
      - label: "Kurs Fiyatları"
        name: "prices"
        file: "kurs-fiyatlarimiz.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      
      - label: "İletişim"
        name: "contact"
        file: "iletisim.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - { label: "Adres", name: "address", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "E-posta", name: "email", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
      
      - label: "Sıkça Sorulan Sorular"
        name: "faq"
        file: "sikca-sorulan-sorular.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
      
      - label: "Duyurular"
        name: "announcements"
        file: "duyurular.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - { label: "Görsel", name: "image", widget: "image" }
      
      - label: "Ekibimiz"
        name: "team"
        file: "ekibimiz.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
          - label: "Ekip Üyeleri"
            name: "members"
            widget: "list"
            fields:
              - { label: "İsim", name: "name", widget: "string" }
              - { label: "Pozisyon", name: "position", widget: "string" }
              - { label: "Fotoğraf", name: "photo", widget: "image" }
              - { label: "Açıklama", name: "description", widget: "text" }

  - name: "images"
    label: "Görseller"
    files:
      - label: "Görsel Yönetimi"
        name: "images"
        file: "assets/img/images.yml"
        fields:
          - { label: "Görsel", name: "image", widget: "image" }
          - { label: "Açıklama", name: "caption", widget: "string" }
          - { label: "Kategori", name: "category", widget: "select", options: ["hero", "team", "news", "other"] }